meta_product_name: "HYBIT"
meta_title: "HYBIT - Habit Builder For Hyper People"
meta_description: "HYBIT helps people with AD(h)D build and keep habits. Through unorthodox methods we help you to reach your goals."
meta_image: "hybit_og_image.jpg" # should exist in `app/assets/images/`
